# Generated by Django 5.1.1 on 2025-02-01 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AirlinesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flight_class',
        ),
    ]
