# Generated by Django 5.1.5 on 2025-02-06 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AirlinesApp', '0002_remove_flight_flight_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
